const SIZES = {
  LOGO_ICON: 30,
  TIMER_FIRST_RATIO: 0.4,
  TIMER_SECOND_RATIO: 0.4,
  TIMER_THIRD_RATIO: 0.2,
  TIMER: 130,
  TIMER_STROKE_WIDTH: 10,
  TIMER_TEXT: 18,
  TIMER_FONTWEIGHT: '600',
  FINISH_ICON: 50,
  PLAY_CANCLE: 40,
  CIRCLE_PLUS_ICON: 24
};

const NAMES = {
  CALENDAR_ICON: 'calendar-check',
  PAUSE_ICON: 'play-pause',
  CANCLE_ICON: 'cancel',
  CIRCLE_PLUS_ICON: 'circle-with-plus'
};

const COLORS = {
  TIMER_FIRST_RENDER: '#004777',
  TIMER_SECOND_RENDER: '#F7B801',
  TIMER_THIRD_RENDER: '#A30000',
  CALENDAR_ICON: '#4cd137',
  BLACK: 'black',
  WHITE: 'white',
  RED: 'red'
};

const STRINGS = {
  SECOND: ' 초'
};

export { SIZES, NAMES, COLORS, STRINGS };
